### ISSUE TITLE
1.16 Checklist / Discussion 

### ISSUE THREAD

**Issue by egold555** [egold555/CorpseReborn#104]
- [x] Thank @ryanopily  for making a 1.16.4 pull request
- [x] Get it so it compiles
- [x] Body laying down 
- [x] Clicking works / basic functionality of corpses
- [ ] Skin layers seem to be broken
- [ ] Player doesn't get removed from tablist sometimes
- [ ] After respawn, player looks very distorted and isn't laying straight
- [ ] Corpses seem to be slow respawning. Good 5-10 second delay before I can see them

**Comment by Veltabex** [comment]
Date: 01/03/2021 00:39:52
CorpseReborn Version: 2.16.0

Server Version: git-Tuinity-"d1db107" (MC: 1.16.4)
Server Type: PAPER_SPIGOT
NMS Version: v1_16_R3
Exception:
java.lang.NullPointerException
    at org.golde.bukkit.corpsereborn.nms.nmsclasses.NMSCorpses_v1_16_R3.loadCorpse(NMSCorpses_v1_16_R3.java:174)
    at org.golde.bukkit.corpsereborn.YMLCorpse.loadAndSpawnAllCorpses(YMLCorpse.java:42)
    at org.golde.bukkit.corpsereborn.Main.onEnable(Main.java:188)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
    at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:470)
    at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:240)
    at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:938)
    at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179)
    at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by egold555** [comment]
> Date: 01/03/2021 00:39:52
> CorpseReborn Version: 2.16.0
> 
> Server Version: git-Tuinity-"d1db107" (MC: 1.16.4)
> Server Type: PAPER_SPIGOT
> NMS Version: v1_16_R3
> Exception:
> java.lang.NullPointerException
> at org.golde.bukkit.corpsereborn.nms.nmsclasses.NMSCorpses_v1_16_R3.loadCorpse(NMSCorpses_v1_16_R3.java:174)
> at org.golde.bukkit.corpsereborn.YMLCorpse.loadAndSpawnAllCorpses(YMLCorpse.java:42)
> at org.golde.bukkit.corpsereborn.Main.onEnable(Main.java:188)
> at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
> at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
> at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
> at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
> at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
> at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:470)
> at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:240)
> at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:938)
> at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179)
> at java.base/java.lang.Thread.run(Thread.java:834)

Have you tried deleting your corpses.yml? Also, I have not texted this plugin with Tuinity, so I would not be too to suprised if it breaks something. 

Could you also do "/cr dump" and send me the pastebin link?

**Comment by kalebbroo** [comment]
Do you take donations? I would love to help keep you motivated to develop/update this plugin. 

i am currently running it on 1.16.5 and its working without any gamebreaking bugs.

**Comment by ryanopily** [comment]
By the way, there seems to be a bug where the corpse spawns +/- one block off of the inventory hitbox... at least when I tested it with the code from my pull request on Jan 4. I haven't worked on it since, though (I've been using the plugin for a minigame that I host for my friends to play, because we're trying to update for 1.16.4)

**Comment by neliyesil2626** [comment]
Is there going to be a version of this plugin for 1.18.2? This would be rather useful for STDSabotage as it is integral to the gameplay.

**Comment by MikeTyson7** [comment]
Hello! I'm "MikeTyson", I'm here to report a bug, I created a "RolePlay" and finished everything except "CorpseReboarn", I installed the "Corpsereboarn" plugin but it doesn't work, I use version 1.16.5, when I do / pl it says "Copsereborn * in red", please, can this solve the problem? I use version 1.16.5, thanks and have a nice day! I'm waiting for an answer, i want download corpsereborn for my server 1.16.5
