### ISSUE TITLE
1.15 Checklist

### ISSUE THREAD

**Issue by egold555** [egold555/CorpseReborn#90]
- [x] Get it so it compiles
- [x] Placing client side bed
- [x] Sleeping in client side bed
- [x] Skin layers seem to be broken
- [x] Player doesn't get removed from tablist sometimes
- [ ] Corpses stand up after relog or world change
- [ ] Relogging removes skin fixes

**Comment by egold555** [comment]
https://github.com/egold555/CorpseReborn/tree/Development

**Comment by Darklom** [comment]
;D
